from tkinter import*
window=Tk()
window.title("product of numbers")
window.geometry("400x400")
frame=Frame(master=window,height=200,width=360,bg="#d0efff")
lbl1=Label(frame,text="number1",bg="#3895D3",fg="white",width=12)
lbl2=Label(frame,text="number2",bg="#3895D3",fg="white",width=12)
n1_entry=Entry(frame)
n2_entry=Entry(frame)
def display():
    n1=n1_entry.get()
    n2=n2_entry.get()
    product=int(n1)*int(n2)
    text_box.insert(END,product)
text_box=Text(bg="#BEBEBE",fg="black")
btn=Button(text="products of numbers",command=display,bg="red")
frame.place(x=20,y=0)
lbl1.place(x=20,y=20)
n1_entry.place(x=150,y=20)
lbl2.place(x=20,y=80)
n2_entry.place(x=150,y=80)
btn.place(x=130,y=210)
text_box.place(y=250)
window.mainloop()